import type { Metadata } from "next";
import Providers from "@/components/providers";
import { IRANYekanX } from "@/theme/fonts";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" dir="rtl">
      <body className={IRANYekanX.variable}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
